//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneTableMultipleEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int IdPublication { get; set; }
        public int IdAuteur { get; set; }
        public string Titre { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
    
        public virtual Auteur Auteur { get; set; }
    }
}
